version: "3"

services:
  tailscale:
    container_name: tailscale
    hostname: tailscale-docker
    image: tailscale/tailscale:latest
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    env_file: tailscale.env

